### ISSUE TITLE
Create a React Component

### ISSUE THREAD

**Issue by unitehenry** [striven-erp/striven-editor#50]
*This one is just for fun... [Striven](https://striven.com/) don't use React.*

```react-striveneditor.js```
```jsx
import { ReactStrivenEditor as StrivenEditor} from '@striven-erp/striven-editor';

function contentComposer() {
     return <StrivenEditor minimal={true} />
}
```

[this](https://reactjs.org/docs/hooks-reference.html#useref) might be useful to get you started

**please use hooks**

**Comment by goatfryed** [comment]
okay, sounds interesting, i'm in.

**Comment by unitehenry** [comment]
@goatfryed Happy Hacking!

**Comment by goatfryed** [comment]
Thanks, @unitehenry.

I've started working on it. I think, the largest difficulty here is to pull in React as an optional dependency. First time working with optional dependencies, so it's really interesting.

In accordance with your example, we'd expect users to pass the editor options as props, but how should prop changes be treated?
Looking at the documentation and api, the options are only given initially and most can't be changed later on.
Should we rather warn the user that it's not supported or rebuild the editor on every prop change?

**Comment by unitehenry** [comment]
@goatfryed You bring up some good points.

To develop this component, I think you should install a ```jsx``` loader as a ```devDependencies``` for webpack to build the component. Then you can you ```npm link @striven-erp/striven-editor``` into a ```create-react-app``` bootstrap. In my opinion, that should be the best way to develop this component.

If the user wants to use a method such as ```getContent``` or ```getFiles```, we should allow them to pass a prop that binds to whatever whatever is passed into it. For example...

```jsx
function discussionThread() {
     let getContent;

     return (
          <>
               <StrivenEditor getContent={(binding) => getContent = binding} />
          </>
     )
}
```

```jsx
props.getContent(editor.getContent)
```

I hope this helps. Feel free to reach out for more help.

**Comment by goatfryed** [comment]
Hey @unitehenry,
I learned a lot about library development and webpack thanks to this issue :D Thank you for the great opportunity.

I want to provide the component with an optional react dependency, so users are free to decide whether they want to use react with striven-editor or not.
To test this, i npm linked to an project that wasn't supposed to have react. Some time later, turns out you need to use resolve.symlinks: false in your demo application without react, or the build will still end up with react.

Now, regarding the implementation of an optional component, see
[stackoverflow - warning on require](https://stackoverflow.com/questions/51131954/warning-when-trying-to-require-a-module-which-is-not-installed-but-not-necessary)
[webpack - optional externals](https://github.com/webpack/webpack/issues/339)

Seems like end-users without the dependency will receive a warning, atleast when bundling their app with webpack. That doesn't seem desireable as well.

What do you think? Or do you have example libs at hand, that support optional third party integration? I don't know about any, where I could get some inspiration.

The component itself is straight forward. Instead of binding dedicated methods, I'd setup a prop that accepts a ref and binds the created instance. The user could useRef and access the whole api, even if it's updated. And then we could think about special cases with smoother support via props.

**Comment by unitehenry** [comment]
Great R&D @goatfryed !

I would point you to look at ```src/index.js``` however.

```js
import './striveneditor.css';

export { default as StrivenEditor } from './striveneditor';
export { default as KoStrivenEditor } from './ko-striveneditor';
export { default as VueStrivenEditor } from './vue-striveneditor.vue';
```

So notice how the ```css``` is always imported and users would be able to ```{ TreeShake }``` the react component out of our ```dist```. So ideally we could use this to export the component like so...

```js
export { default as ReactStrivenEditor } from './react-striveneditor.jsx';
``` 

Maybe this raises other concerns, but I think it a fine path to take. Let me know your thoughts.

**Comment by goatfryed** [comment]
Since the treeshaking isn't always applied in dev builds and could still not helpful warnings, I've settled with just providing a dedicated file, that also imports the css.
If you see no issues with potential warnings being raised, then we can still add
```
try {
  require('react');
  export * from './react-integration';
} catch (error) {
  // optional dependency
}
```
